### ISSUE TITLE
Line Endings

### ISSUE THREAD

**Issue by Ryokin** [hundredrabbits/Left#61]
When you edit or write a file, new lines are \n (LF), regardless of the current OS. On Windows new lines are \r\n (CR LF). Would it be a possibility to add some command line to switch between line endings when saving?

**Comment by neauoire** [comment]
Oh really? I had no idea. How different does it look? Let's say you save a file and re-open it, are the line breaks not showing? I can definitely add a flag to convert them into \r\n.

**Comment by Ryokin** [comment]
I tried checking some text editor and see what it shows. Basically the only one that has difficulties with different line endings is Windows Notepad (WordPad works fine) that is how I noticed it. So this might be the least of the issues.

**Comment by neauoire** [comment]
Let's keep this issue open, maybe someone else will notice this with other apps.

**Comment by neauoire** [comment]
I believe that @JakubValtar has resolved this issue.

**Comment by JakubValtar** [comment]
Not really, I only fixed discard, because it would compare the version with \n with the version from disk and would find that they always differ because of the line endings.

Handling line endings is a mess, most editors have a settings you can switch per document. They also auto detect the endings when opening the document and keep them the same when you save it.

**Comment by neauoire** [comment]
This should be resolved with the latest update.
